# Site settings
title: founderX Blog
header-img: img/home-bg.jpg
email: 546714415@qq.com
copyright_name: founder is LZY
description: "Share the experience of Tech and legitimately rebuild the world"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: Alex Liu
github_username:  founderx4
facebook_username: Alex Liu
email_username:  546714415@qq.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
